library(ggplot2)
library(tidyverse)
library(viridis)
library(stringr)
options(scipen = 100)

ip = snakemake@wildcards[["ip"]]
filename_chip = snakemake@input[["mat"]]
window = snakemake@params[["binsize"]]
upstream = snakemake@params[["upstream"]]
downstream = snakemake@params[["downstream"]]
bodylength = snakemake@params[["bodylength"]]
align = snakemake@params[["align"]]
outpath = snakemake@output[["matname"]]
plotname = snakemake@output[["plotname"]]

#Function to get IP from the column name
get_ip = function(string)
{
  start=0;end=0;
  start = head(gregexpr("-",string)[[1]],1) + 1
  end = head(gregexpr("_",string)[[1]],1) - 1
  ip= substr(string, start, end)
  return(ip)
}
#Breadth of the matrix belonging to each sample
feature_length = (upstream + downstream + bodylength)/window

#Define where tick marks are required
if(bodylength==0)
{
  ticks = c(0,upstream/window+0.5,feature_length)
  labels = c(-upstream,align,downstream)
} else {
  ticks = c(0,upstream/window+0.5,(upstream+bodylength)/window+0.5,feature_length)
  labels = c(-upstream,"TSS","TES",downstream)
}


#Read in the matrix: The input matrix is generated by deeptools computematrix
df_chip = filename_chip %>% read_tsv(skip=3, col_names = F)
nsamples = ncol(df_chip)/feature_length

#Get column names separately
col_line = filename_chip %>% read.table(head=F, skip =2, nrows=1, stringsAsFactors=F)
col_line = col_line[-1]
names = unlist(lapply(col_line, get_ip))
names = paste(names, rep(1:feature_length,nsamples), sep="_")
colnames(df_chip) = names


#Melt the matrix
melt_matrix = gather(df_chip, key=name, value=value)

#Split the "name" column to get gtype and x value
sample_and_x = as.data.frame(melt_matrix$name %>% str_split_fixed("_",2),stringsAsFactors=F)
colnames(sample_and_x) = c("sample","x")
gtype = str_split_fixed(sample_and_x$sample,"-[:digit:]",2)[,1]
melt_matrix = cbind(melt_matrix,sample_and_x,gtype)
melt_matrix$x = as.numeric(melt_matrix$x)

melt_matrix$gtype = factor(melt_matrix$gtype, levels = unique(melt_matrix$gtype))

#Plot the metagene
g=ggplot(melt_matrix, aes(x,value, color = gtype, group = sample))+
  stat_summary(fun.data=mean_cl_normal, geom="smooth", alpha = 0.3)+
  ylab("") + xlab("Distance (kb)")+ ggtitle(ip)+
  scale_x_continuous(breaks=ticks, labels=labels)+
  scale_color_viridis("",option="viridis",discrete=T)+
  ylim(0,NA)+
  theme_bw()+
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size=25,hjust=0.5),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15))

ggsave(plot=g, filename = plotname, width = 10, height = 5, units = "in", dpi = 300)

write_tsv(melt_matrix,outpath,col_names = T)



